### ISSUE TITLE
Benchmarking with Ecto

### ISSUE THREAD

**Issue by rodrigues** [alco/benchfella#43]
More of a n00b question actually, perhaps resulting in an addition to README 😉

I created a bench in my phoenix app to see how a particular query was going.

At first, the bench just did `import Ecto.Query` and went for it.

To make it work, I did:

```elixir
  setup_all do: Application.ensure_all_started(:my_app)
  teardown_all _, do: Application.stop(:my_app)
```

Is this how you would do as well?

Perhaps this would be a question from others, valuable to the README, that as for now uses only simple elixir as example, not interacting with an app.

I'd be glad to contribute to the docs if this is the expected approach.

Thanks!

-----

**EDIT**: this ended up being a more elegant way:

`mix do app.start, bench`

**Comment by alco** [comment]
Hi.

Benchfella calls `app.start --no-start` to set up the load paths. That is done on purpose because the scope of the tool has been comparing algorithms rather than components of a full-on application with databases and stuff. You can think of it as being most suitable for measuring stateless functions – ones that don't expect any data to be preserved after their execution.

With Ecto, you have a bunch of stateful components: the worker pool, the database server itself. There could also be a cache for queries, the semantics of which would most likely affect the results you get from Benchfella.

My suggestion for you is to be very careful in drawing conclusions from benchmarking Ecto. And thanks for bringing this up, I will think about what to add to the Readme to make Benchfella's goals clearer.

**Comment by rodrigues** [comment]
Thanks for the reply, @alco! Learning a bunch from you guys 💜
